"""add face embedding to teacher

Revision ID: 3c4484ac7c90
Revises: 0512955848c3
Create Date: 2026-02-27 00:26:11.272399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4484ac7c90'
down_revision = '0512955848c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_embedding', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('face_embedding')

    # ### end Alembic commands ###
