"""added read and created_at to notification

Revision ID: 4717ccc119ff
Revises: 924f3d129b11
Create Date: 2026-02-26 12:09:22.792170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4717ccc119ff'
down_revision = '924f3d129b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('is_read')
        batch_op.drop_column('role')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('read')

    # ### end Alembic commands ###
