"""added file to assignment submission

Revision ID: 74076fb154a1
Revises: 8ec3344c4772
Create Date: 2026-02-27 11:24:43.719005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74076fb154a1'
down_revision = '8ec3344c4772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['academic_assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_submissions')
    # ### end Alembic commands ###
