"""added file to academic assignment

Revision ID: 8ec3344c4772
Revises: 37fa1d483b86
Create Date: 2026-02-27 11:19:19.302877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec3344c4772'
down_revision = '37fa1d483b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_assignments', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
