"""add face image fields

Revision ID: 9d1aba82a72a
Revises: 0e01fee9f923
Create Date: 2026-02-24 18:42:45.787375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1aba82a72a'
down_revision = '0e01fee9f923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_image_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('face_encoding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encoding', sa.BLOB(), nullable=True))
        batch_op.drop_column('face_image_path')

    # ### end Alembic commands ###
