"""added file to academic assignment

Revision ID: a488921d081b
Revises: 74076fb154a1
Create Date: 2026-02-27 13:04:37.544233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a488921d081b'
down_revision = '74076fb154a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.alter_column('assignment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('assignment_submissions_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'academic_assignments', ['assignment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assignment_submissions_ibfk_1'), 'academic_assignments', ['assignment_id'], ['id'])
        batch_op.alter_column('assignment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
